In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from os import listdir
from os.path import isdir
from numpy import savez_compressed
from numpy import asarray
from numpy import load
from numpy import expand_dims
from random import choice
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import Normalizer
import scipy.stats as stats
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.model_selection import validation_curve
from sklearn import metrics
from sklearn.metrics import roc_curve
from sklearn.metrics import auc 

In [13]:
df1 = pd.read_excel('Train_Dataset.xlsx',header=None)
df2 = pd.read_excel('Test_Dataset.xlsx',header=None)

In [ ]:
df1.head(5)

0         1         2         3         4         5         6    \
0 -0.989334  0.677734 -0.871576  0.173565  0.220217 -0.143696 -0.143366   
1 -0.988267  0.567458 -0.457154 -0.224233  0.104860  0.086843 -0.061979   
2 -0.984238  0.633877 -0.622412 -0.135349  0.183578  0.040601 -0.091090   
3 -0.962648  0.732686 -0.740453 -0.054269  0.161035  0.029010 -0.198132   
4 -0.174504 -0.142899 -0.122296 -0.104739 -0.081728 -0.074655 -0.074369   

        7         8         9    ...       551       552       553       554  \
0  0.029637  0.027641 -0.099184  ... -0.886425 -0.868541 -0.710233 -0.861877   
1 -0.062611  0.044861  0.048686  ... -0.908397 -0.924827 -0.873059 -0.894867   
2 -0.003801  0.099604  0.036936  ... -0.919548 -0.905741 -0.845054 -0.906142   
3 -0.067336  0.110686  0.035114  ... -0.917198 -0.876513 -0.866033 -0.892919   
4 -0.068611 -0.056634 -0.047551  ...  0.999209  0.996125  0.999968  0.999984   

        555       556       557       558       559  560  
0 -0.882453 -0.595948 -0.864924 -0.888609 -0.915554    1  
1 -0.881452 -0.923901 -0.921514 -0.928568 -0.942388    1  
2 -0.915819 -0.935343 -0.925553 -0.924076 -0.956214    1  
3 -0.905738 -0.887519 -0.894219 -0.789015 -0.931389    1  
4 -0.967017  0.999782  0.999996  0.999999  0.999662    1  

[5 rows x 561 columns]

In [14]:
df2.head(5)

0         1         2         3         4         5         6    \
0 -0.978189  0.710088 -0.829166  0.179836  0.213549 -0.174499 -0.141603   
1 -0.956427  0.736591 -0.810389  0.177924  0.226957 -0.158520 -0.120338   
2 -0.982409  0.711293 -0.796207  0.201274  0.215307 -0.157286 -0.191578   
3 -0.986997  0.725616 -0.841995  0.455185  0.024101 -0.301596 -0.052146   
4 -0.990537  0.715020 -0.831138  0.415829  0.170204 -0.197180 -0.004549   

        7         8         9    ...       551       552       553       554  \
0  0.082213  0.080289 -0.040281  ... -0.898618 -0.910135 -0.925555 -0.878335   
1  0.030130 -0.000590 -0.121863  ... -0.929851 -0.911448 -0.923216 -0.911816   
2  0.002043  0.039717 -0.052825  ... -0.914425 -0.915563 -0.932089 -0.927137   
3  0.089462 -0.014578 -0.071108  ... -0.836533 -0.842375 -0.874840 -0.843406   
4  0.156982  0.081569 -0.026335  ... -0.919978 -0.911977 -0.891032 -0.897665   

        555       556       557       558       559  560  
0 -0.912158 -0.904237 -0.947651 -0.947223 -0.952495    1  
1 -0.920951 -0.954833 -0.963964 -0.924532 -0.950519    1  
2 -0.921729 -0.949606 -0.960689 -0.926864 -0.955616    1  
3 -0.842403 -0.707724 -0.812811 -0.723752 -0.895866    1  
4 -0.883679 -0.896315 -0.942841 -0.917079 -0.944649    1  

[5 rows x 561 columns]

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Columns: 561 entries, 0 to 560
dtypes: float64(560), int64(1)
memory usage: 4.3 MB


In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487 entries, 0 to 486
Columns: 561 entries, 0 to 560
dtypes: float64(560), int64(1)
memory usage: 2.1 MB


In [17]:
df1[560].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int64)

In [18]:
df1.columns

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            551, 552, 553, 554, 555, 556, 557, 558, 559, 560],
           dtype='int64', length=561)

## Creating random sample for Subject Target

In [70]:
from random import seed
from random import choice
#seed random number generator
#seed(1) - Helps generate one similiar constant type of output
#prepare a sequence
sequence = [i for i in range(1, 22)]
print(sequence)
for _ in range(3):
    selection = choice(sequence)
    print(selection)
    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
15
9
8


# Subject 1

In [36]:
df1.rename(columns = {560:'Target'}, inplace=True)
df2.rename(columns = {560:'Target'}, inplace=True)


In [37]:
df1.head(5)

0         1         2         3         4         5         6  \
0 -0.989334  0.677734 -0.871576  0.173565  0.220217 -0.143696 -0.143366   
1 -0.988267  0.567458 -0.457154 -0.224233  0.104860  0.086843 -0.061979   
2 -0.984238  0.633877 -0.622412 -0.135349  0.183578  0.040601 -0.091090   
3 -0.962648  0.732686 -0.740453 -0.054269  0.161035  0.029010 -0.198132   
4 -0.174504 -0.142899 -0.122296 -0.104739 -0.081728 -0.074655 -0.074369   

          7         8         9  ...       551       552       553       554  \
0  0.029637  0.027641 -0.099184  ... -0.886425 -0.868541 -0.710233 -0.861877   
1 -0.062611  0.044861  0.048686  ... -0.908397 -0.924827 -0.873059 -0.894867   
2 -0.003801  0.099604  0.036936  ... -0.919548 -0.905741 -0.845054 -0.906142   
3 -0.067336  0.110686  0.035114  ... -0.917198 -0.876513 -0.866033 -0.892919   
4 -0.068611 -0.056634 -0.047551  ...  0.999209  0.996125  0.999968  0.999984   

        555       556       557       558       559  Target  
0 -0.882453 -0.595948 -0.864924 -0.888609 -0.915554       1  
1 -0.881452 -0.923901 -0.921514 -0.928568 -0.942388       1  
2 -0.915819 -0.935343 -0.925553 -0.924076 -0.956214       1  
3 -0.905738 -0.887519 -0.894219 -0.789015 -0.931389       1  
4 -0.967017  0.999782  0.999996  0.999999  0.999662       1  

[5 rows x 561 columns]

In [38]:
df1['Target'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int64)

In [47]:
def target_column(num):
    for i in num:
        if i == 1:
            return i
        else:
            return False

## Concantenating Selected Random samples for Subject 1

In [80]:
df_1 = df1[df1['Target']==1]
df_8 = df1[df1['Target']==8]
df_9 = df1[df1['Target']==9]
df_15 = df1[df1['Target']==15]

new_sub1 = pd.concat([df_1,df_8,df_9,df_15],axis=0)
new_sub1

0         1         2         3         4         5         6  \
0   -0.989334  0.677734 -0.871576  0.173565  0.220217 -0.143696 -0.143366   
1   -0.988267  0.567458 -0.457154 -0.224233  0.104860  0.086843 -0.061979   
2   -0.984238  0.633877 -0.622412 -0.135349  0.183578  0.040601 -0.091090   
3   -0.962648  0.732686 -0.740453 -0.054269  0.161035  0.029010 -0.198132   
4   -0.174504 -0.142899 -0.122296 -0.104739 -0.081728 -0.074655 -0.074369   
..        ...       ...       ...       ...       ...       ...       ...   
706 -0.919536  0.717880 -0.943519  0.702024 -0.756069  0.122980  0.346970   
707 -0.986917  0.682041 -0.721074 -0.227883  0.201898  0.122437 -0.093646   
708 -0.964557  0.728283 -0.923708  0.424315 -0.089209 -0.375494 -0.026881   
709 -0.962922  0.695800 -0.862400  0.071727  0.201287 -0.179612 -0.264099   
710 -0.960230  0.732717 -0.903000  0.485542 -0.147115 -0.452847 -0.059544   

            7         8         9  ...       551       552       553  \
0    0.029637  0.027641 -0.099184  ... -0.886425 -0.868541 -0.710233   
1   -0.062611  0.044861  0.048686  ... -0.908397 -0.924827 -0.873059   
2   -0.003801  0.099604  0.036936  ... -0.919548 -0.905741 -0.845054   
3   -0.067336  0.110686  0.035114  ... -0.917198 -0.876513 -0.866033   
4   -0.068611 -0.056634 -0.047551  ...  0.999209  0.996125  0.999968   
..        ...       ...       ...  ...       ...       ...       ...   
706 -0.187919 -0.222133  0.078284  ... -0.827490 -0.811599 -0.833079   
707 -0.100815  0.035756  0.106790  ... -0.813698 -0.863703 -0.864646   
708  0.150520  0.044482 -0.028812  ... -0.879284 -0.902925 -0.903340   
709 -0.061334  0.083640  0.034879  ... -0.866003 -0.856044 -0.905641   
710  0.161476  0.035323 -0.060736  ... -0.875604 -0.874882 -0.887415   

          554       555       556       557       558       559  Target  
0   -0.861877 -0.882453 -0.595948 -0.864924 -0.888609 -0.915554       1  
1   -0.894867 -0.881452 -0.923901 -0.921514 -0.928568 -0.942388       1  
2   -0.906142 -0.915819 -0.935343 -0.925553 -0.924076 -0.956214       1  
3   -0.892919 -0.905738 -0.887519 -0.894219 -0.789015 -0.931389       1  
4    0.999984 -0.967017  0.999782  0.999996  0.999999  0.999662       1  
..        ...       ...       ...       ...       ...       ...     ...  
706 -0.836940 -0.754231 -0.739837 -0.803195 -0.626832 -1.266578      15  
707 -0.887042 -0.905136 -0.896297 -0.898654 -0.928767 -0.925936      15  
708 -0.909735 -0.922687 -0.922441 -0.892887 -0.887572 -0.856023      15  
709 -0.903293 -0.906649 -0.879021 -0.848907 -0.866947 -0.918493      15  
710 -0.907871 -0.906536 -0.854453 -0.839030 -0.922616 -0.905640      15  

[188 rows x 561 columns]

In [81]:
new_sub1['Target'].unique()

array([ 1,  8,  9, 15], dtype=int64)

In [82]:
new_sub1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 188 entries, 0 to 710
Columns: 561 entries, 0 to Target
dtypes: float64(560), int64(1)
memory usage: 825.4 KB


In [83]:
new_sub1['Target'].value_counts()

15    48
9     48
8     48
1     44
Name: Target, dtype: int64

In [84]:
new_sub1['Target'] = new_sub1['Target'].map({1 : 1, 8: 0, 9: 0, 15: 0})

In [85]:
new_sub1['Target'].unique()

array([1, 0], dtype=int64)

In [87]:
#Show records where Target is 1
real = new_sub1[new_sub1['Target'] == 1]
real.head()


0         1         2         3         4         5         6  \
0 -0.989334  0.677734 -0.871576  0.173565  0.220217 -0.143696 -0.143366   
1 -0.988267  0.567458 -0.457154 -0.224233  0.104860  0.086843 -0.061979   
2 -0.984238  0.633877 -0.622412 -0.135349  0.183578  0.040601 -0.091090   
3 -0.962648  0.732686 -0.740453 -0.054269  0.161035  0.029010 -0.198132   
4 -0.174504 -0.142899 -0.122296 -0.104739 -0.081728 -0.074655 -0.074369   

          7         8         9  ...       551       552       553       554  \
0  0.029637  0.027641 -0.099184  ... -0.886425 -0.868541 -0.710233 -0.861877   
1 -0.062611  0.044861  0.048686  ... -0.908397 -0.924827 -0.873059 -0.894867   
2 -0.003801  0.099604  0.036936  ... -0.919548 -0.905741 -0.845054 -0.906142   
3 -0.067336  0.110686  0.035114  ... -0.917198 -0.876513 -0.866033 -0.892919   
4 -0.068611 -0.056634 -0.047551  ...  0.999209  0.996125  0.999968  0.999984   

        555       556       557       558       559  Target  
0 -0.882453 -0.595948 -0.864924 -0.888609 -0.915554       1  
1 -0.881452 -0.923901 -0.921514 -0.928568 -0.942388       1  
2 -0.915819 -0.935343 -0.925553 -0.924076 -0.956214       1  
3 -0.905738 -0.887519 -0.894219 -0.789015 -0.931389       1  
4 -0.967017  0.999782  0.999996  0.999999  0.999662       1  

[5 rows x 561 columns]

In [88]:
#Showing records where the remaining Targets bear 0 as Imposter
imposter = new_sub1[new_sub1['Target'] == 0]
imposter

0         1         2         3         4         5         6  \
328 -0.970152  0.375055 -0.939387  0.594652  0.527084 -0.007864 -0.269716   
329 -0.972266  0.365199 -0.967341  0.689590  0.342092 -0.311692 -0.153202   
330 -0.969340  0.623034 -0.750718  0.663994 -0.169509 -0.447433  0.118007   
331 -0.935793  0.381102 -0.969931  0.322044  0.312816 -0.084256 -0.210017   
332 -0.978864  0.647709 -0.610898  0.039540  0.210079 -0.084734 -0.140190   
..        ...       ...       ...       ...       ...       ...       ...   
706 -0.919536  0.717880 -0.943519  0.702024 -0.756069  0.122980  0.346970   
707 -0.986917  0.682041 -0.721074 -0.227883  0.201898  0.122437 -0.093646   
708 -0.964557  0.728283 -0.923708  0.424315 -0.089209 -0.375494 -0.026881   
709 -0.962922  0.695800 -0.862400  0.071727  0.201287 -0.179612 -0.264099   
710 -0.960230  0.732717 -0.903000  0.485542 -0.147115 -0.452847 -0.059544   

            7         8         9  ...       551       552       553  \
328 -0.090225  0.165680  0.187907  ... -0.739536 -0.885239 -1.347072   
329  0.264522  0.233932 -0.065577  ... -0.701460 -0.658404 -1.164105   
330  0.323640 -0.088855 -0.314201  ... -0.855527 -0.821493 -0.935907   
331 -0.083700  0.065242  0.064283  ... -0.762540 -0.589013 -1.109682   
332  0.075404  0.149578 -0.042342  ... -0.840914 -0.824087 -0.955391   
..        ...       ...       ...  ...       ...       ...       ...   
706 -0.187919 -0.222133  0.078284  ... -0.827490 -0.811599 -0.833079   
707 -0.100815  0.035756  0.106790  ... -0.813698 -0.863703 -0.864646   
708  0.150520  0.044482 -0.028812  ... -0.879284 -0.902925 -0.903340   
709 -0.061334  0.083640  0.034879  ... -0.866003 -0.856044 -0.905641   
710  0.161476  0.035323 -0.060736  ... -0.875604 -0.874882 -0.887415   

          554       555       556       557       558       559  Target  
328 -0.856537 -1.275747 -1.047940 -1.006283 -0.692604 -0.999023       0  
329 -0.681845 -0.882182 -0.998934 -0.964177 -0.544549 -0.983774       0  
330 -0.810752 -0.564070 -0.796014 -0.706040 -0.905599 -0.927920       0  
331 -0.760571 -1.053787 -1.000891 -0.589704 -0.709439 -0.855125       0  
332 -0.865448 -0.831928 -0.689670 -0.650367 -0.906958 -0.882427       0  
..        ...       ...       ...       ...       ...       ...     ...  
706 -0.836940 -0.754231 -0.739837 -0.803195 -0.626832 -1.266578       0  
707 -0.887042 -0.905136 -0.896297 -0.898654 -0.928767 -0.925936       0  
708 -0.909735 -0.922687 -0.922441 -0.892887 -0.887572 -0.856023       0  
709 -0.903293 -0.906649 -0.879021 -0.848907 -0.866947 -0.918493       0  
710 -0.907871 -0.906536 -0.854453 -0.839030 -0.922616 -0.905640       0  

[144 rows x 561 columns]