In [486]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from random import choice
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import roc_curve
from sklearn.decomposition import  PCA
from sklearn.preprocessing import StandardScaler


import warnings
warnings.filterwarnings("ignore")

In [487]:
df = pd.read_excel('Train_RestClosed_Biometrics.xlsx',header=None)
df.head(5)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Columns: 562 entries, 0 to 561
dtypes: float64(560), int64(2)
memory usage: 8.4 MB
None


In [488]:
df.drop(561,1, inplace=True)

In [489]:
df.head(5)

0         1         2         3         4         5         6    \
0 -0.999226  0.002347  0.000383  0.000016  0.000416 -0.000108 -0.000598   
1 -0.999227  0.000758  0.000864  0.000637  0.000409  0.000352  0.000542   
2 -0.999215  0.001454  0.000775 -0.000121 -0.000777 -0.000783 -0.000203   
3 -0.999227  0.001050  0.000486 -0.000134 -0.000456 -0.000346  0.000140   
4 -0.999217 -0.000594 -0.000429  0.000166  0.000845  0.001161  0.001033   

        7         8         9    ...         551        552        553  \
0  0.000050  0.001248  0.001038  ...   17.915858  14.042900  22.009515   
1  0.000676  0.000440 -0.000119  ... -145.064462 -16.658530 -24.035528   
2  0.000500  0.000822  0.000616  ...  -19.585202 -14.675864 -31.486464   
3  0.000782  0.001285  0.001282  ...   -7.412917  -7.818255 -11.713346   
4  0.000494 -0.000084 -0.000448  ...   -6.393234  -6.826698  -8.593136   

         554         555        556        557        558        559  560  
0  28.770245    9.993780   6.576365  15.720314   7.852062   8.861143    1  
1  57.730532  191.936356   7.793836  33.896247   3.553457  20.672913    1  
2 -60.325533 -272.218604   9.209448  42.144403   4.082240  20.512868    1  
3  -8.955803   -9.297744 -10.400048  -9.255250 -11.016431 -15.208149    1  
4  -9.570859   -7.218773  -7.283716  -7.051959  -6.953481 -12.507100    1  

[5 rows x 561 columns]

In [490]:
df.rename(columns = {560:'Target'}, inplace=True)
print(df['Target'].unique())
df.describe()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


0            1            2            3            4  \
count  1962.000000  1962.000000  1962.000000  1962.000000  1962.000000   
mean     -0.965875     0.633873    -0.534381     0.199050     0.160097   
std       0.063824     0.324207     0.307469     0.284217     0.191353   
min      -0.999418    -0.320190    -0.936939    -0.397983    -0.767641   
25%      -0.989275     0.654850    -0.770208    -0.002498     0.000817   
50%      -0.970021     0.778190    -0.659457     0.113443     0.210158   
75%      -0.959206     0.835873    -0.354083     0.429690     0.309837   
max      -0.002383     0.934300     0.149601     0.894877     0.487911   

                 5            6            7            8            9  ...  \
count  1962.000000  1962.000000  1962.000000  1962.000000  1962.000000  ...   
mean     -0.054167    -0.073747    -0.005692     0.005750    -0.027626  ...   
std       0.168694     0.113198     0.100740     0.075869     0.069632  ...   
min      -0.617287    -0.360364    -0.254651    -0.462296    -0.365841  ...   
25%      -0.191279    -0.159513    -0.080195    -0.027073    -0.065742  ...   
50%      -0.000230    -0.080074    -0.001960     0.001285    -0.001665  ...   
75%       0.064991     0.000658     0.053839     0.051402     0.012955  ...   
max       0.266482     0.451442     0.453086     0.327179     0.201303  ...   

               551          552           553          554          555  \
count  1962.000000  1962.000000   1962.000000  1962.000000  1962.000000   
mean     -1.949788    -1.427521     28.513481    -1.287785    -1.189334   
std       6.704258    10.413219   1112.119934     7.701526    18.211491   
min    -145.064462  -389.563193   -694.131562   -86.624231  -327.534398   
25%      -0.936750    -0.931313     -0.935075    -0.936555    -0.957408   
50%      -0.917263    -0.911020     -0.917064    -0.916796    -0.947850   
75%      -0.889748    -0.862366     -0.887571    -0.888744    -0.928823   
max      61.156411   111.516182  48830.739875   205.092349   448.332786   

               556          557          558          559       Target  
count  1962.000000  1962.000000  1962.000000  1962.000000  1962.000000  
mean     -1.608207    -0.347157    -0.882891     0.537365    10.978084  
std      20.720284    22.810270    13.347676    68.006297     6.027138  
min    -664.297879  -295.835914   -95.958366  -165.379147     1.000000  
25%      -0.934876    -0.940461    -0.938372    -0.952986     6.000000  
50%      -0.911298    -0.927029    -0.919982    -0.937314    11.000000  
75%      -0.845945    -0.901632    -0.873112    -0.918500    16.000000  
max     144.915192   612.492324   502.782246  2952.137009    21.000000  

[8 rows x 561 columns]

In [491]:
df.isnull().any().any()
df.isnull().sum().sum()

6552

## Data Cleaning

In [492]:
mean_score = df.mean()

In [493]:
df.fillna(mean_score, inplace=True)

In [494]:
df.isnull().sum().sum()

0

In [495]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Columns: 561 entries, 0 to Target
dtypes: float64(560), int64(1)
memory usage: 8.4 MB


In [496]:
def generate_auth_dataset(df, subj, ratio=3):
        subj_df = df.copy()
        subj_df.loc[(subj_df['Target'] != subj), 'Target'] = 0
        subj_df.loc[(subj_df['Target'] == subj), 'Target'] = 1
        gen_df = subj_df[subj_df['Target'] == 1]
        no_gen = gen_df.shape[0]
        imp_df = subj_df[subj_df['Target'] == 0].sample(n = no_gen * ratio)
        auth_df = pd.concat([gen_df, imp_df])
        return auth_df

In [497]:
df1 = generate_auth_dataset(df,1)

In [498]:
df1['Target'].value_counts()

0    279
1     93
Name: Target, dtype: int64

In [499]:
scaler = StandardScaler()
X_Feat, y_train = df1.iloc[:, :-1].values, df1.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data = scaler.transform(X_Feat)

In [500]:
pca = PCA(n_components=30)
pca.fit(scaled_data)
x_pca = pca.transform(scaled_data)
x_pca.shape

(372, 30)

In [501]:
df_test = pd.read_excel('Test_RestClosed_Biometrics.xlsx',header=None)

In [502]:
print(df_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 971 entries, 0 to 970
Columns: 561 entries, 0 to 560
dtypes: float64(560), int64(1)
memory usage: 4.2 MB
None


In [503]:
df_test.isnull().sum().sum()

3360

In [504]:
df_test.dropna(0,inplace=True)

In [505]:
df_test.isnull().sum().sum()

0

In [506]:
df_test.rename(columns = {560:'Target'}, inplace=True)

In [507]:
df1_test = generate_auth_dataset(df_test, 1, ratio=3)
df1_test['Target'].unique()

array([1, 0], dtype=int64)

In [508]:
df1_test['Target'].value_counts()

0    138
1     46
Name: Target, dtype: int64

In [509]:
scaler = StandardScaler()
X_Feat_test, y_test = df1_test.iloc[:, :-1].values, df1_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test = scaler.transform(X_Feat_test)

In [510]:
pca = PCA(n_components=30)
pca.fit(scaled_data_test)
x_pca_test = pca.transform(scaled_data_test)
x_pca_test.shape

(184, 30)

In [511]:
X_test = x_pca_test
X_train = x_pca

In [512]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test1 = accuracy_score(y_test,predictions)

[[135   3]
 [ 45   1]]


              precision    recall  f1-score   support

           0       0.75      0.98      0.85       138
           1       0.25      0.02      0.04        46

    accuracy                           0.74       184
   macro avg       0.50      0.50      0.44       184
weighted avg       0.62      0.74      0.65       184



In [513]:
df2 = generate_auth_dataset(df,2, ratio=3)
df2_test = generate_auth_dataset(df_test,2, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df2.iloc[:, :-1].values, df2.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data2 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df2_test.iloc[:, :-1].values, df2_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test2 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data2)
x_pca2 = pca.transform(scaled_data2)

pca = PCA(n_components=30)
pca.fit(scaled_data_test2)
x_pca_test2 = pca.transform(scaled_data_test2)

X_test = x_pca_test2
X_train = x_pca2

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test2 = accuracy_score(y_test,predictions)

[[115   8]
 [ 41   0]]


              precision    recall  f1-score   support

           0       0.74      0.93      0.82       123
           1       0.00      0.00      0.00        41

    accuracy                           0.70       164
   macro avg       0.37      0.47      0.41       164
weighted avg       0.55      0.70      0.62       164



In [514]:
df3 = generate_auth_dataset(df,3, ratio=3)
df3_test = generate_auth_dataset(df_test,3, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df3.iloc[:, :-1].values, df3.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data3 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df3_test.iloc[:, :-1].values, df3_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test3 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data3)
x_pca3 = pca.transform(scaled_data3)

pca = PCA(n_components=30)
pca.fit(scaled_data_test3)
x_pca_test3 = pca.transform(scaled_data_test3)

X_test = x_pca_test3
X_train = x_pca3

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test3 = accuracy_score(y_test,predictions)

[[119   4]
 [ 29  12]]


              precision    recall  f1-score   support

           0       0.80      0.97      0.88       123
           1       0.75      0.29      0.42        41

    accuracy                           0.80       164
   macro avg       0.78      0.63      0.65       164
weighted avg       0.79      0.80      0.76       164



In [515]:
df4 = generate_auth_dataset(df,4, ratio=3)
df4_test = generate_auth_dataset(df_test,4, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df4.iloc[:, :-1].values, df4.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data4 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df4_test.iloc[:, :-1].values, df4_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test4 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data4)
x_pca4 = pca.transform(scaled_data4)

pca = PCA(n_components=30)
pca.fit(scaled_data_test4)
x_pca_test4 = pca.transform(scaled_data_test4)

X_test = x_pca_test4
X_train = x_pca4

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test4 = accuracy_score(y_test,predictions)

[[117  21]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.72      0.85      0.78       138
           1       0.00      0.00      0.00        46

    accuracy                           0.64       184
   macro avg       0.36      0.42      0.39       184
weighted avg       0.54      0.64      0.58       184



In [516]:
df5 = generate_auth_dataset(df,5, ratio=3)
df5_test = generate_auth_dataset(df_test,5, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df5.iloc[:, :-1].values, df5.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data5 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df5_test.iloc[:, :-1].values, df5_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test5 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data)
x_pca5 = pca.transform(scaled_data5)

pca = PCA(n_components=65)
pca.fit(scaled_data_test5)
x_pca_test5 = pca.transform(scaled_data_test5)

X_test = x_pca_test5
X_train = x_pca5

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test5 = accuracy_score(y_test,predictions)

[[138   0]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.75      1.00      0.86       138
           1       0.00      0.00      0.00        46

    accuracy                           0.75       184
   macro avg       0.38      0.50      0.43       184
weighted avg       0.56      0.75      0.64       184



In [517]:
df6 = generate_auth_dataset(df,6, ratio=3)
df6_test = generate_auth_dataset(df_test,6, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df6.iloc[:, :-1].values, df6.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data6 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df6_test.iloc[:, :-1].values, df6_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test6 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data6)
x_pca6 = pca.transform(scaled_data6)

pca = PCA(n_components=65)
pca.fit(scaled_data_test6)
x_pca_test6 = pca.transform(scaled_data_test6)

X_test = x_pca_test6
X_train = x_pca6

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test6 = accuracy_score(y_test,predictions)

[[125  13]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.73      0.91      0.81       138
           1       0.00      0.00      0.00        46

    accuracy                           0.68       184
   macro avg       0.37      0.45      0.40       184
weighted avg       0.55      0.68      0.61       184



In [518]:
df7 = generate_auth_dataset(df,7, ratio=3)
df7_test = generate_auth_dataset(df_test,7, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df7.iloc[:, :-1].values, df7.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data7 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df7_test.iloc[:, :-1].values, df7_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test7 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data7)
x_pca7 = pca.transform(scaled_data7)

pca = PCA(n_components=65)
pca.fit(scaled_data_test7)
x_pca_test7 = pca.transform(scaled_data_test7)

X_test = x_pca_test7
X_train = x_pca7

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test7 = accuracy_score(y_test,predictions)

[[138   0]
 [  9  37]]


              precision    recall  f1-score   support

           0       0.94      1.00      0.97       138
           1       1.00      0.80      0.89        46

    accuracy                           0.95       184
   macro avg       0.97      0.90      0.93       184
weighted avg       0.95      0.95      0.95       184



In [519]:
df8 = generate_auth_dataset(df,8, ratio=3)
df8_test = generate_auth_dataset(df_test,8, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df8.iloc[:, :-1].values, df8.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data8 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df8_test.iloc[:, :-1].values, df8_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test8 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data8)
x_pca8 = pca.transform(scaled_data8)

pca = PCA(n_components=65)
pca.fit(scaled_data_test8)
x_pca_test8 = pca.transform(scaled_data_test6)

X_test = x_pca_test8
X_train = x_pca8

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test8 = accuracy_score(y_test,predictions)

[[133   5]
 [ 45   1]]


              precision    recall  f1-score   support

           0       0.75      0.96      0.84       138
           1       0.17      0.02      0.04        46

    accuracy                           0.73       184
   macro avg       0.46      0.49      0.44       184
weighted avg       0.60      0.73      0.64       184



In [520]:
df9 = generate_auth_dataset(df,9, ratio=3)
df9_test = generate_auth_dataset(df_test,9, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df9.iloc[:, :-1].values, df9.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data9 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df9_test.iloc[:, :-1].values, df9_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test9 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data9)
x_pca9 = pca.transform(scaled_data9)

pca = PCA(n_components=30)
pca.fit(scaled_data_test9)
x_pca_test9 = pca.transform(scaled_data_test9)

X_test = x_pca_test9
X_train = x_pca9

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test9 = accuracy_score(y_test,predictions)

[[125  13]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.73      0.91      0.81       138
           1       0.00      0.00      0.00        46

    accuracy                           0.68       184
   macro avg       0.37      0.45      0.40       184
weighted avg       0.55      0.68      0.61       184



In [521]:
df10 = generate_auth_dataset(df,10, ratio=3)
df10_test = generate_auth_dataset(df_test,10, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df10.iloc[:, :-1].values, df10.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data10 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df10_test.iloc[:, :-1].values, df10_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test10 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data10)
x_pca10 = pca.transform(scaled_data10)

pca = PCA(n_components=65)
pca.fit(scaled_data_test10)
x_pca_test10 = pca.transform(scaled_data_test10)

X_test = x_pca_test10
X_train = x_pca10

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test10 = accuracy_score(y_test,predictions)

[[135   3]
 [ 42   4]]


              precision    recall  f1-score   support

           0       0.76      0.98      0.86       138
           1       0.57      0.09      0.15        46

    accuracy                           0.76       184
   macro avg       0.67      0.53      0.50       184
weighted avg       0.71      0.76      0.68       184



In [522]:
df11 = generate_auth_dataset(df,11, ratio=3)
df11_test = generate_auth_dataset(df_test,11, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df11.iloc[:, :-1].values, df11.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data11 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df11_test.iloc[:, :-1].values, df11_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test11 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data11)
x_pca11 = pca.transform(scaled_data11)

pca = PCA(n_components=65
)
pca.fit(scaled_data_test11)
x_pca_test11 = pca.transform(scaled_data_test11)

X_test = x_pca_test11
X_train = x_pca11

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test11 = accuracy_score(y_test,predictions)

[[114  24]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.71      0.83      0.77       138
           1       0.00      0.00      0.00        46

    accuracy                           0.62       184
   macro avg       0.36      0.41      0.38       184
weighted avg       0.53      0.62      0.57       184



In [523]:
df12 = generate_auth_dataset(df,12, ratio=3)
df12_test = generate_auth_dataset(df_test,12, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df12.iloc[:, :-1].values, df12.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data12 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df12_test.iloc[:, :-1].values, df12_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test12 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data12)
x_pca12 = pca.transform(scaled_data12)

pca = PCA(n_components=30)
pca.fit(scaled_data_test12)
x_pca_test12 = pca.transform(scaled_data_test12)

X_test = x_pca_test12
X_train = x_pca12

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test12 = accuracy_score(y_test,predictions)

[[101  37]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.69      0.73      0.71       138
           1       0.00      0.00      0.00        46

    accuracy                           0.55       184
   macro avg       0.34      0.37      0.35       184
weighted avg       0.52      0.55      0.53       184



In [524]:
df13 = generate_auth_dataset(df,13, ratio=3)
df13_test = generate_auth_dataset(df_test,13, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df13.iloc[:, :-1].values, df13.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data13 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df13_test.iloc[:, :-1].values, df13_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test13 = scaler.transform(X_Feat_test)

pca = PCA(n_components=30)
pca.fit(scaled_data13)
x_pca13 = pca.transform(scaled_data13)

pca = PCA(n_components=30)
pca.fit(scaled_data_test13)
x_pca_test13 = pca.transform(scaled_data_test13)

X_test = x_pca_test13
X_train = x_pca13

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test13 = accuracy_score(y_test,predictions)

[[136   2]
 [ 18  28]]


              precision    recall  f1-score   support

           0       0.88      0.99      0.93       138
           1       0.93      0.61      0.74        46

    accuracy                           0.89       184
   macro avg       0.91      0.80      0.83       184
weighted avg       0.90      0.89      0.88       184



In [525]:
df14 = generate_auth_dataset(df,14, ratio=3)
df14_test = generate_auth_dataset(df_test,14, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df14.iloc[:, :-1].values, df14.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data14 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df14_test.iloc[:, :-1].values, df14_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test14 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data14)
x_pca14 = pca.transform(scaled_data14)

pca = PCA(n_components=65)
pca.fit(scaled_data_test14)
x_pca_test14 = pca.transform(scaled_data_test14)

X_test = x_pca_test14
X_train = x_pca14

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test14 = accuracy_score(y_test,predictions)

[[114  24]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.71      0.83      0.77       138
           1       0.00      0.00      0.00        46

    accuracy                           0.62       184
   macro avg       0.36      0.41      0.38       184
weighted avg       0.53      0.62      0.57       184



In [526]:
df15 = generate_auth_dataset(df,15, ratio=3)
df15_test = generate_auth_dataset(df_test,15, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df15.iloc[:, :-1].values, df15.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data15 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df15_test.iloc[:, :-1].values, df15_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test15 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data15)
x_pca15 = pca.transform(scaled_data15)

pca = PCA(n_components=65)
pca.fit(scaled_data_test15)
x_pca_test15 = pca.transform(scaled_data_test15)

X_test = x_pca_test15
X_train = x_pca15

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test15 = accuracy_score(y_test,predictions)

[[133   5]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.74      0.96      0.84       138
           1       0.00      0.00      0.00        46

    accuracy                           0.72       184
   macro avg       0.37      0.48      0.42       184
weighted avg       0.56      0.72      0.63       184



In [527]:
df16 = generate_auth_dataset(df,16, ratio=3)
df16_test = generate_auth_dataset(df_test,16, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df16.iloc[:, :-1].values, df16.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data16 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df16_test.iloc[:, :-1].values, df16_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test16 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data16)
x_pca16 = pca.transform(scaled_data16)

pca = PCA(n_components=65)
pca.fit(scaled_data_test16)
x_pca_test16 = pca.transform(scaled_data_test16)

X_test = x_pca_test16
X_train = x_pca16

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test16 = accuracy_score(y_test,predictions)

[[123  15]
 [ 13  33]]


              precision    recall  f1-score   support

           0       0.90      0.89      0.90       138
           1       0.69      0.72      0.70        46

    accuracy                           0.85       184
   macro avg       0.80      0.80      0.80       184
weighted avg       0.85      0.85      0.85       184



In [528]:
df17 = generate_auth_dataset(df,17, ratio=3)
df17_test = generate_auth_dataset(df_test,17, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df15.iloc[:, :-1].values, df17.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data17 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df17_test.iloc[:, :-1].values, df17_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test17 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data17)
x_pca17 = pca.transform(scaled_data17)

pca = PCA(n_components=65)
pca.fit(scaled_data_test17)
x_pca_test17 = pca.transform(scaled_data_test17)

X_test = x_pca_test17
X_train = x_pca17

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test17 = accuracy_score(y_test,predictions)

[[136   2]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.75      0.99      0.85       138
           1       0.00      0.00      0.00        46

    accuracy                           0.74       184
   macro avg       0.37      0.49      0.43       184
weighted avg       0.56      0.74      0.64       184



In [529]:
df18 = generate_auth_dataset(df,18, ratio=3)
df18_test = generate_auth_dataset(df_test,18, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df18.iloc[:, :-1].values, df18.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data18 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df18_test.iloc[:, :-1].values, df18_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test18 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data18)
x_pca18 = pca.transform(scaled_data18)

pca = PCA(n_components=65)
pca.fit(scaled_data_test18)
x_pca_test18 = pca.transform(scaled_data_test18)

X_test = x_pca_test18
X_train = x_pca18

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test18 = accuracy_score(y_test,predictions)

[[85 53]
 [46  0]]


              precision    recall  f1-score   support

           0       0.65      0.62      0.63       138
           1       0.00      0.00      0.00        46

    accuracy                           0.46       184
   macro avg       0.32      0.31      0.32       184
weighted avg       0.49      0.46      0.47       184



In [530]:
df19 = generate_auth_dataset(df,19, ratio=3)
df19_test = generate_auth_dataset(df_test,19, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df19.iloc[:, :-1].values, df19.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data19 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df19_test.iloc[:, :-1].values, df19_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test19 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data19)
x_pca19 = pca.transform(scaled_data19)

pca = PCA(n_components=65)
pca.fit(scaled_data_test19)
x_pca_test19 = pca.transform(scaled_data_test19)

X_test = x_pca_test19
X_train = x_pca19

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test19 = accuracy_score(y_test,predictions)

[[120   9]
 [ 43   0]]


              precision    recall  f1-score   support

           0       0.74      0.93      0.82       129
           1       0.00      0.00      0.00        43

    accuracy                           0.70       172
   macro avg       0.37      0.47      0.41       172
weighted avg       0.55      0.70      0.62       172



In [531]:
df20 = generate_auth_dataset(df,20, ratio=3)
df20_test = generate_auth_dataset(df_test,20, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df20.iloc[:, :-1].values, df20.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data20 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df20_test.iloc[:, :-1].values, df20_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test20 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data20)
x_pca20 = pca.transform(scaled_data20)

pca = PCA(n_components=65)
pca.fit(scaled_data_test20)
x_pca_test20 = pca.transform(scaled_data_test20)

X_test = x_pca_test20
X_train = x_pca20

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test20 = accuracy_score(y_test,predictions)

[[128   4]
 [ 44   0]]


              precision    recall  f1-score   support

           0       0.74      0.97      0.84       132
           1       0.00      0.00      0.00        44

    accuracy                           0.73       176
   macro avg       0.37      0.48      0.42       176
weighted avg       0.56      0.73      0.63       176



In [532]:
df21 = generate_auth_dataset(df,21, ratio=3)
df21_test = generate_auth_dataset(df_test,21, ratio=3)

scaler = StandardScaler()
X_Feat, y_train = df21.iloc[:, :-1].values, df21.iloc[:, -1].values
scaler.fit(X_Feat)
scaled_data21 = scaler.transform(X_Feat)

scaler = StandardScaler()
X_Feat_test, y_test = df21_test.iloc[:, :-1].values, df21_test.iloc[:, -1].values
scaler.fit(X_Feat_test)
scaled_data_test21 = scaler.transform(X_Feat_test)

pca = PCA(n_components=65)
pca.fit(scaled_data21)
x_pca21 = pca.transform(scaled_data21)

pca = PCA(n_components=65)
pca.fit(scaled_data_test21)
x_pca_test21 = pca.transform(scaled_data_test21)

X_test = x_pca_test21
X_train = x_pca21

model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

score_test21 = accuracy_score(y_test,predictions)

[[123  15]
 [ 46   0]]


              precision    recall  f1-score   support

           0       0.73      0.89      0.80       138
           1       0.00      0.00      0.00        46

    accuracy                           0.67       184
   macro avg       0.36      0.45      0.40       184
weighted avg       0.55      0.67      0.60       184



In [533]:
data = {'Score Name':['Subject 1', 'Subject 2', 'Subject 3', 'Subject 4', 'Subject 5', 'Subject 6','Subject 7', 'Subject 8', 'Subject 9', 'Subject 10', 'Subject 11', 'Subject 12', 'Subject 13', 'Subject 14', 'Subject 15', 'Subject 16', 'Subject 17', 'Subject 18', 'Subject 19', 'Subject 20', 'Subject 21'],
        'Scores':[score_test1*100, score_test2*100, score_test3*100, score_test4*100, score_test5*100, score_test6*100, score_test7*100, score_test8*100, score_test9*100, score_test10*100, score_test11*100, score_test12*100, score_test13*100, score_test14*100, score_test15*100, score_test16*100, score_test17*100, score_test18*100, score_test19*100, score_test20*100, score_test21*100]}

df_score = pd.DataFrame(data)
#df_score.set_index('Score Name 1', inplace=True)    
df_score_round1 = df_score.copy()
df_score_round2 = df_score.copy()
df_score_round3 = df_score.copy()
df_score_round4 = df_score.copy()
df_score_round5 = df_score.copy()
df_score_round6 = df_score.copy()
df_score_round7 = df_score.copy()
df_score_round8 = df_score.copy()
df_score_round9 = df_score.copy()
df_score_round10 = df_score.copy()       

In [534]:
result1 = pd.concat([df_score_round1,df_score_round2,df_score_round3,df_score_round4,df_score_round5,df_score_round6,df_score_round7,df_score_round8,df_score_round9,df_score_round10], axis=1)
result1

Scores 1   Scores 2   Scores 3   Scores 4   Scores 5   Scores 6  \
Subject 1   70.108696  71.739130  75.000000  67.391304  73.913043  73.913043   
Subject 2   90.853659  93.902439  62.804878  60.975610  92.682927  62.804878   
Subject 3   73.780488  70.731707  65.853659  64.634146  70.731707  72.560976   
Subject 4   64.673913  65.217391  72.282609  66.304348  92.934783  71.195652   
Subject 5   74.456522  75.000000  75.000000  70.108696  73.913043  74.456522   
Subject 6   72.282609  67.391304  68.478261  65.760870  86.956522  73.369565   
Subject 7   61.413043  85.869565  82.065217  83.152174  81.521739  81.521739   
Subject 8   60.326087  77.717391  70.108696  69.565217  72.826087  85.326087   
Subject 9   65.217391  65.217391  64.673913  79.347826  80.434783  74.456522   
Subject 10  63.043478  69.021739  72.282609  61.413043  65.217391  64.673913   
Subject 11  68.478261  76.630435  63.586957  79.347826  69.565217  64.673913   
Subject 12  92.391304  93.478261  60.326087  90.217391  88.586957  94.565217   
Subject 13  80.434783  74.456522  83.152174  73.369565  82.608696  84.239130   
Subject 14  74.456522  64.130435  62.500000  75.000000  75.000000  75.000000   
Subject 15  72.282609  75.000000  76.630435  69.021739  71.195652  71.195652   
Subject 16  86.413043  93.478261  88.043478  92.391304  79.891304  78.260870   
Subject 17  68.478261  69.565217  72.826087  71.195652  75.000000  73.913043   
Subject 18  61.413043  60.869565  57.065217  60.326087  55.978261  62.500000   
Subject 19  80.232558  62.790698  68.604651  94.767442  71.511628  68.023256   
Subject 20  70.454545  78.977273  75.568182  71.022727  75.568182  77.272727   
Subject 21  73.369565  82.065217  89.673913  67.391304  78.260870  82.608696   

             Scores 7   Scores 8   Scores 9  Scores 10  
Subject 1   75.543478  71.739130  60.326087  73.913043  
Subject 2   95.121951  69.512195  92.682927  70.121951  
Subject 3   68.902439  74.390244  75.000000  79.878049  
Subject 4   69.021739  78.260870  92.391304  63.586957  
Subject 5   75.000000  63.586957  67.934783  75.000000  
Subject 6   71.739130  70.108696  72.826087  67.934783  
Subject 7   87.500000  89.673913  73.369565  95.108696  
Subject 8   69.565217  74.456522  68.478261  72.826087  
Subject 9   72.826087  73.913043  74.456522  67.934783  
Subject 10  69.565217  63.043478  70.652174  75.543478  
Subject 11  67.391304  71.739130  66.304348  61.956522  
Subject 12  90.760870  67.391304  56.521739  54.891304  
Subject 13  82.065217  76.086957  76.630435  89.130435  
Subject 14  61.956522  75.000000  64.673913  61.956522  
Subject 15  83.152174  67.934783  70.652174  72.282609  
Subject 16  76.086957  71.195652  89.673913  84.782609  
Subject 17  82.608696  64.673913  74.456522  73.913043  
Subject 18  61.413043  54.891304  55.978261  46.195652  
Subject 19  66.860465  72.093023  70.348837  69.767442  
Subject 20  72.159091  74.431818  71.590909  72.727273  
Subject 21  85.326087  57.065217  83.152174  66.847826

In [535]:
ss1 = result1.iloc[0].mean()
ss2 = result1.iloc[1].mean()
ss3 = result1.iloc[2].mean()
ss4 = result1.iloc[3].mean()
ss5 = result1.iloc[4].mean()
ss6 = result1.iloc[5].mean()
ss7 = result1.iloc[6].mean()
ss8 = result1.iloc[7].mean()
ss9 = result1.iloc[8].mean()
ss10 = result1.iloc[9].mean()
ss11 = result1.iloc[10].mean()
ss12 = result1.iloc[11].mean()
ss13 = result1.iloc[12].mean()
ss14 = result1.iloc[13].mean()
ss15 = result1.iloc[14].mean()
ss16 = result1.iloc[15].mean()
ss17 = result1.iloc[16].mean()
ss18 = result1.iloc[17].mean()
ss19 = result1.iloc[18].mean()
ss20 = result1.iloc[19].mean()
ss21 = result1.iloc[20].mean()


In [537]:
test_result1 = pd.DataFrame({'Stimulus 2': [ss1,ss2,ss3,ss4,ss5,ss6,ss7,ss8,ss9,ss10,ss11,ss12,ss13,ss14,ss15,ss16,ss17,ss18,ss19,ss20,ss21]})
test_result1

Stimulus 2
0    71.358696
1    79.146341
2    71.646341
3    73.586957
4    72.445652
5    71.684783
6    82.119565
7    72.119565
8    71.847826
9    67.445652
10   68.967391
11   78.913043
12   80.217391
13   68.967391
14   72.934783
15   84.021739
16   72.663043
17   57.663043
18   72.500000
19   73.977273
20   76.576087

test_result1 = pd.DataFrame({'Stimulus 1': [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21],'Stimulus 2': [ss1,ss2,ss3,ss4,ss5,ss6,ss7,ss8,ss9,ss10,ss11,ss12,ss13,ss14,ss15,ss16,ss17,ss18,ss19,ss20,ss21]})
test_result1.transpose()